Allow entering DNS and peers allowed ip individually, update screenshot

diff --git a/wizard-run b/wizard-run
--- a/wizard-run
+++ b/wizard-run
@@ -323,11 +323,13 @@ load () {
 
     # Inputfield allowed ips for peers QR code
     eval "peersallowedips=($($run show configuration commands | awk '/wireguard-wizard-peers-allowed-ips/ {print $5}'))"
-    peersallowedips="\"peers-allowed-ips\":\"$peersallowedips\""
+    peersallowedips="\"peers-allowed-ips\":[\"$peersallowedips\"]"
+    peersallowedips=${peersallowedips//,/\",\"}
 
     # Inputfield DNS for peers QR code
     eval "peersdns=($($run show configuration commands | awk '/wireguard-wizard-peers-dns/ {print $5}'))"
-    peersdns="\"peers-dns\":\"$peersdns\""
+    peersdns="\"peers-dns\":[\"$peersdns\"]"
+    peersdns=${peersdns//,/\",\"}
 
     # Peers:
     # get current wireguard configuration and return configured values to wizard.html
@@ -436,8 +438,10 @@ apply () {
     parse listenport '."listen-port"'
     parse routeallowedips '."route-allowed-ips"'
     mapfile -t ipaddress < <(cat $INPUT | jq -c '."ipaddress"' | sed 's/,/ /g;s/\[//;s/\]//;s/\"//g')
-    parse peersallowedips '."peers-allowed-ips"'
-    parse peersdns '."peers-dns"'
+    #parse peersallowedips '."peers-allowed-ips"'
+    peersallowedips=$(cat $INPUT | jq -c '."peers-allowed-ips"' | sed 's/\[//;s/\]//;s/\"//g')
+    #parse peersdns '."peers-dns"'
+    peersdns=$(cat $INPUT | jq -c '."peers-dns"' | sed 's/\[//;s/\]//;s/\"//g')
     parse pubkeys '."peerlist"[]."public-key"'
     parse descriptions '."peerlist"[]."description"'
     parse endpoints '."peerlist"[]."endpoint"'
@@ -507,8 +511,8 @@ apply () {
                 fi
                 if [ -n "${ipaddress}" ] && [ "${ipaddress}" != "null" ]; then
                     for oneipaddress in ${ipaddress}; do
-                        if ! $cmd set $wgcfg ${interfaces[0]} address $oneipaddress; then
-                            echo "set $wgcfg ${interfaces[0]} address $oneipaddress failed." >> $log
+                        if ! $cmd set $wgcfg ${interfaces[0]} address "$oneipaddress"; then
+                            echo "set $wgcfg ${interfaces[0]} address \"$oneipaddress\" failed." >> $log
                             ret=1
                             break 2
                         fi
@@ -518,16 +522,16 @@ apply () {
                     if ! $cmd set custom-attribute wireguard-wizard-peers-allowed-ips; then
                         echo "set custom-attribute wireguard-wizard-peers-allowed-ips failed." >> $log
                     fi
-                    if ! $cmd set custom-attribute wireguard-wizard-peers-allowed-ips value $peersallowedips; then
-                        echo "set custom-attribute wireguard-wizard-peers-allowed-ips value $peersallowedips failed." >> $log
+                    if ! $cmd set custom-attribute wireguard-wizard-peers-allowed-ips value "$peersallowedips"; then
+                        echo "set custom-attribute wireguard-wizard-peers-allowed-ips value \"$peersallowedips\" failed." >> $log
                     fi
                 fi
                 if [ -n "$peersdns" ]; then
                     if ! $cmd set custom-attribute wireguard-wizard-peers-dns; then
                         echo "set custom-attribute wireguard-wizard-peers-dns failed." >> $log
                     fi
-                    if ! $cmd set custom-attribute wireguard-wizard-peers-dns value $peersdns; then
-                        echo "set custom-attribute wireguard-wizard-peers-dns value $peersdns failed." >> $log
+                    if ! $cmd set custom-attribute wireguard-wizard-peers-dns value "$peersdns"; then
+                        echo "set custom-attribute wireguard-wizard-peers-dns value \"$peersdns\" failed." >> $log
                     fi
                 fi
                 j=0
